x-app: &default-app
  image: agroportal/ontoportal_web_ui:test
  env_file:
    - ".env"
  tty: true
  volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node:/node_modules
    - rails_cache:/app/tmp/cache
    - assets:/app/public/assets
    - /var/run/docker.sock:/var/run/docker.sock
  tmpfs:
    - /tmp
    - /app/tmp/pids

services:
  db:
    image: "mysql:8.0"
    networks:
      - default
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3  

  cache:
    image: memcached:latest
    restart: unless-stopped
    command: [ "-m", "1024" ]
    networks:
      - default
    ports:
      - "11211:11211"
  node:
    <<: *default-app
    command: "yarn build --watch"

  rails:
    <<: *default-app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      node:
        condition: service_started
    links:
      - db
      - cache
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: db
      CACHE_HOST: cache
    ports:
      - "3000:3000"
  test:
    <<: *default-app
    depends_on:
      - db
      - cache
      - chrome-server
    network_mode: 'host'
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: 127.0.0.1
      CACHE_HOST: 127.0.0.1
  chrome-server:
    image: selenium/standalone-chrome:112.0-chromedriver-112.0-grid-4.9.0-20230421
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"

volumes:
  mysql-data:
  bundle:
  rails_cache:
  assets:
  node:
