test:
  ontologies:
    STY:
      repository: 'jvendetti/bioportal-nigms-u24'

development:
  ontologies:
    ENVO:
      repository: 'hrshdhgd/envo'
    GO:
      repository: 'hrshdhgd/go-ontology'
    MONDO:
      repository: 'hrshdhgd/mondo'
    UBERON:
      repository: 'hrshdhgd/uberon'

staging:
  ontologies:
    ENVO:
      repository: 'hrshdhgd/envo'
    GO:
      repository: 'hrshdhgd/go-ontology'
    MONDO:
      repository: 'hrshdhgd/mondo'
    UBERON:
      repository: 'hrshdhgd/uberon'

production:
  ontologies:
    ENVO:
      repository: 'EnvironmentOntology/envo'
    GO:
      repository: 'geneontology/go-ontology'
    MONDO:
      repository: 'monarch-initiative/mondo'
    UBERON:
      repository: 'obophenotype/uberon'

appliance:
  ontologies: null