shared:
  links:
    about: 'https://www.bioontology.org/about-us/'
    cite: 'https://www.bioontology.org/about-us/#cite-bioportal'
    cookies: 'https://www.bioontology.org/terms/#use-of-cookies'
    facebook: 'https://www.facebook.com/National-Center-for-Biomedical-Ontology-127444774011153/'
    github: 'http://github.com/ncbo'
    help: 'https://www.bioontology.org/wiki/BioPortal_Help'
    help_annotator: 'https://www.bioontology.org/wiki/BioPortal_Help#Annotator_Tab'
    help_mappings: 'https://www.bioontology.org/wiki/BioPortal_Help#Mappings_Tab'
    help_ontology_browse: 'https://www.bioontology.org/wiki/BioPortal_Help#Browse_Tab'
    help_projects: 'https://www.bioontology.org/wiki/BioPortal_Help#Projects_Tab'
    help_recommender: 'https://www.bioontology.org/wiki/BioPortal_Help#Recommender_Tab'
    help_search: 'https://www.bioontology.org/wiki/BioPortal_Help#Search_Tab'
    help_slice: 'https://www.bioontology.org//wiki/BioPortal_Help#slice_definition'
    metrics: 'https://www.bioontology.org/wiki/Ontology_Metrics'
    mission: 'https://www.bioontology.org/about-us/#mission'
    privacy_policy: 'https://www.bioontology.org/privacy/'
    rest_api: 'http://data.bioontology.org/documentation'
    team: 'https://www.bioontology.org/about-us/#team'
    terms: 'https://www.bioontology.org/terms/'
    twitter: 'http://twitter.com/bioontology'
    virtual_appliance: 'https://ontoportal.github.io/documentation/administration'
    widgets: 'http://www.bioontology.org/wiki/NCBO_Widgets'
    wiki: 'https://www.bioontology.org/wiki/'
    mappings: 'https://www.bioontology.org/wiki/BioPortal_Help#Mappings_Tab'
    metadata_help: 'https://doc.jonquetlab.lirmm.fr/share/32c082ff-97f5-45f4-bafe-05f41c9a5ce4'

development:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'
  purl:
    enabled: true
    host: 'purl.bioontology.org'
    prefix: 'https://purl.bioontology.org/ontology'

test:
  purl:
    enabled: false
    host: 'stagepurl.bioontology.org'
    prefix: 'https://stagepurl.bioontology.org/ontology'

staging:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'
  purl:
    enabled: true
    host: 'stagepurl.bioontology.org'
    prefix: 'https://stagepurl.bioontology.org/ontology'

production:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'
  purl:
    enabled: true
    host: 'purl.bioontology.org'
    prefix: 'https://purl.bioontology.org/ontology'

appliance:
  links:
    release_notes: 'https://www.bioontology.org/wiki/BioPortal_Virtual_Appliance_Release_Notes'
  purl:
    # Set enabled to true if you're running a PURL server to provide PURLs for ontologies and concepts
    # in your OntoPortal instance
    enabled: false
    host: 'purl.example.org'
    # PURL URLs are generated using the prefix + the ontology acronym
    prefix: 'https://purl.example.org/ontology'
