shared:
  links:
    about: 'https://www.bioontology.org/about-us/'
    cite: 'https://www.bioontology.org/about-us/#cite-bioportal'
    facebook: 'https://www.facebook.com/National-Center-for-Biomedical-Ontology-127444774011153/'
    github: 'http://github.com/ncbo'
    help: 'https://www.bioontology.org/wiki/BioPortal_Help'
    metrics: 'https://www.bioontology.org/wiki/Ontology_Metrics'
    mission: 'https://www.bioontology.org/about-us/#mission'
    privacy_policy: 'https://www.bioontology.org/privacy/'
    rest_api: 'http://data.bioontology.org/documentation'
    team: 'https://www.bioontology.org/about-us/#team'
    terms: 'https://www.bioontology.org/terms/'
    twitter: 'http://twitter.com/bioontology'
    virtual_appliance: 'https://ontoportal.github.io/administration/'
    widgets: 'http://www.bioontology.org/wiki/NCBO_Widgets'
    wiki: 'https://www.bioontology.org/wiki/'
    mappings: 'https://www.bioontology.org/wiki/BioPortal_Help#Mappings_Tab'

development:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'

staging:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'

production:
  links:
    release_notes: 'https://github.com/ncbo/bioportal_web_ui/releases'

appliance:
  links:
    release_notes: 'https://www.bioontology.org/wiki/BioPortal_Virtual_Appliance_Release_Notes'
